/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Allenatori
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-09-16T10:12:51.528Z")
public class Allenatori {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("isAdmin")
  private Boolean isAdmin = null;

  @SerializedName("nome")
  private String nome = null;

  @SerializedName("nuovoNome")
  private String nuovoNome = null;

  @SerializedName("ordine")
  private Integer ordine = null;

  @SerializedName("pwd")
  private String pwd = null;

  public Allenatori id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Allenatori isAdmin(Boolean isAdmin) {
    this.isAdmin = isAdmin;
    return this;
  }

   /**
   * Get isAdmin
   * @return isAdmin
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsAdmin() {
    return isAdmin;
  }

  public void setIsAdmin(Boolean isAdmin) {
    this.isAdmin = isAdmin;
  }

  public Allenatori nome(String nome) {
    this.nome = nome;
    return this;
  }

   /**
   * Get nome
   * @return nome
  **/
  @ApiModelProperty(value = "")
  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }

  public Allenatori nuovoNome(String nuovoNome) {
    this.nuovoNome = nuovoNome;
    return this;
  }

   /**
   * Get nuovoNome
   * @return nuovoNome
  **/
  @ApiModelProperty(value = "")
  public String getNuovoNome() {
    return nuovoNome;
  }

  public void setNuovoNome(String nuovoNome) {
    this.nuovoNome = nuovoNome;
  }

  public Allenatori ordine(Integer ordine) {
    this.ordine = ordine;
    return this;
  }

   /**
   * Get ordine
   * @return ordine
  **/
  @ApiModelProperty(value = "")
  public Integer getOrdine() {
    return ordine;
  }

  public void setOrdine(Integer ordine) {
    this.ordine = ordine;
  }

  public Allenatori pwd(String pwd) {
    this.pwd = pwd;
    return this;
  }

   /**
   * Get pwd
   * @return pwd
  **/
  @ApiModelProperty(value = "")
  public String getPwd() {
    return pwd;
  }

  public void setPwd(String pwd) {
    this.pwd = pwd;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Allenatori allenatori = (Allenatori) o;
    return Objects.equals(this.id, allenatori.id) &&
        Objects.equals(this.isAdmin, allenatori.isAdmin) &&
        Objects.equals(this.nome, allenatori.nome) &&
        Objects.equals(this.nuovoNome, allenatori.nuovoNome) &&
        Objects.equals(this.ordine, allenatori.ordine) &&
        Objects.equals(this.pwd, allenatori.pwd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, isAdmin, nome, nuovoNome, ordine, pwd);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Allenatori {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isAdmin: ").append(toIndentedString(isAdmin)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    nuovoNome: ").append(toIndentedString(nuovoNome)).append("\n");
    sb.append("    ordine: ").append(toIndentedString(ordine)).append("\n");
    sb.append("    pwd: ").append(toIndentedString(pwd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

