/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TimeZone;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * Calendar
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-09-16T10:12:51.528Z")
public class Calendar {
  @SerializedName("calendarType")
  private String calendarType = null;

  @SerializedName("firstDayOfWeek")
  private Integer firstDayOfWeek = null;

  @SerializedName("lenient")
  private Boolean lenient = null;

  @SerializedName("minimalDaysInFirstWeek")
  private Integer minimalDaysInFirstWeek = null;

  @SerializedName("time")
  private OffsetDateTime time = null;

  @SerializedName("timeInMillis")
  private Long timeInMillis = null;

  @SerializedName("timeZone")
  private TimeZone timeZone = null;

  @SerializedName("weekDateSupported")
  private Boolean weekDateSupported = null;

  @SerializedName("weekYear")
  private Integer weekYear = null;

  @SerializedName("weeksInWeekYear")
  private Integer weeksInWeekYear = null;

  public Calendar calendarType(String calendarType) {
    this.calendarType = calendarType;
    return this;
  }

   /**
   * Get calendarType
   * @return calendarType
  **/
  @ApiModelProperty(value = "")
  public String getCalendarType() {
    return calendarType;
  }

  public void setCalendarType(String calendarType) {
    this.calendarType = calendarType;
  }

  public Calendar firstDayOfWeek(Integer firstDayOfWeek) {
    this.firstDayOfWeek = firstDayOfWeek;
    return this;
  }

   /**
   * Get firstDayOfWeek
   * @return firstDayOfWeek
  **/
  @ApiModelProperty(value = "")
  public Integer getFirstDayOfWeek() {
    return firstDayOfWeek;
  }

  public void setFirstDayOfWeek(Integer firstDayOfWeek) {
    this.firstDayOfWeek = firstDayOfWeek;
  }

  public Calendar lenient(Boolean lenient) {
    this.lenient = lenient;
    return this;
  }

   /**
   * Get lenient
   * @return lenient
  **/
  @ApiModelProperty(value = "")
  public Boolean isLenient() {
    return lenient;
  }

  public void setLenient(Boolean lenient) {
    this.lenient = lenient;
  }

  public Calendar minimalDaysInFirstWeek(Integer minimalDaysInFirstWeek) {
    this.minimalDaysInFirstWeek = minimalDaysInFirstWeek;
    return this;
  }

   /**
   * Get minimalDaysInFirstWeek
   * @return minimalDaysInFirstWeek
  **/
  @ApiModelProperty(value = "")
  public Integer getMinimalDaysInFirstWeek() {
    return minimalDaysInFirstWeek;
  }

  public void setMinimalDaysInFirstWeek(Integer minimalDaysInFirstWeek) {
    this.minimalDaysInFirstWeek = minimalDaysInFirstWeek;
  }

  public Calendar time(OffsetDateTime time) {
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getTime() {
    return time;
  }

  public void setTime(OffsetDateTime time) {
    this.time = time;
  }

  public Calendar timeInMillis(Long timeInMillis) {
    this.timeInMillis = timeInMillis;
    return this;
  }

   /**
   * Get timeInMillis
   * @return timeInMillis
  **/
  @ApiModelProperty(value = "")
  public Long getTimeInMillis() {
    return timeInMillis;
  }

  public void setTimeInMillis(Long timeInMillis) {
    this.timeInMillis = timeInMillis;
  }

  public Calendar timeZone(TimeZone timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * Get timeZone
   * @return timeZone
  **/
  @ApiModelProperty(value = "")
  public TimeZone getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(TimeZone timeZone) {
    this.timeZone = timeZone;
  }

  public Calendar weekDateSupported(Boolean weekDateSupported) {
    this.weekDateSupported = weekDateSupported;
    return this;
  }

   /**
   * Get weekDateSupported
   * @return weekDateSupported
  **/
  @ApiModelProperty(value = "")
  public Boolean isWeekDateSupported() {
    return weekDateSupported;
  }

  public void setWeekDateSupported(Boolean weekDateSupported) {
    this.weekDateSupported = weekDateSupported;
  }

  public Calendar weekYear(Integer weekYear) {
    this.weekYear = weekYear;
    return this;
  }

   /**
   * Get weekYear
   * @return weekYear
  **/
  @ApiModelProperty(value = "")
  public Integer getWeekYear() {
    return weekYear;
  }

  public void setWeekYear(Integer weekYear) {
    this.weekYear = weekYear;
  }

  public Calendar weeksInWeekYear(Integer weeksInWeekYear) {
    this.weeksInWeekYear = weeksInWeekYear;
    return this;
  }

   /**
   * Get weeksInWeekYear
   * @return weeksInWeekYear
  **/
  @ApiModelProperty(value = "")
  public Integer getWeeksInWeekYear() {
    return weeksInWeekYear;
  }

  public void setWeeksInWeekYear(Integer weeksInWeekYear) {
    this.weeksInWeekYear = weeksInWeekYear;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Calendar calendar = (Calendar) o;
    return Objects.equals(this.calendarType, calendar.calendarType) &&
        Objects.equals(this.firstDayOfWeek, calendar.firstDayOfWeek) &&
        Objects.equals(this.lenient, calendar.lenient) &&
        Objects.equals(this.minimalDaysInFirstWeek, calendar.minimalDaysInFirstWeek) &&
        Objects.equals(this.time, calendar.time) &&
        Objects.equals(this.timeInMillis, calendar.timeInMillis) &&
        Objects.equals(this.timeZone, calendar.timeZone) &&
        Objects.equals(this.weekDateSupported, calendar.weekDateSupported) &&
        Objects.equals(this.weekYear, calendar.weekYear) &&
        Objects.equals(this.weeksInWeekYear, calendar.weeksInWeekYear);
  }

  @Override
  public int hashCode() {
    return Objects.hash(calendarType, firstDayOfWeek, lenient, minimalDaysInFirstWeek, time, timeInMillis, timeZone, weekDateSupported, weekYear, weeksInWeekYear);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Calendar {\n");
    
    sb.append("    calendarType: ").append(toIndentedString(calendarType)).append("\n");
    sb.append("    firstDayOfWeek: ").append(toIndentedString(firstDayOfWeek)).append("\n");
    sb.append("    lenient: ").append(toIndentedString(lenient)).append("\n");
    sb.append("    minimalDaysInFirstWeek: ").append(toIndentedString(minimalDaysInFirstWeek)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    timeInMillis: ").append(toIndentedString(timeInMillis)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    weekDateSupported: ").append(toIndentedString(weekDateSupported)).append("\n");
    sb.append("    weekYear: ").append(toIndentedString(weekYear)).append("\n");
    sb.append("    weeksInWeekYear: ").append(toIndentedString(weeksInWeekYear)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

