/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Configurazione
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-09-16T10:12:51.528Z")
public class Configurazione {
  @SerializedName("budget")
  private Integer budget = null;

  @SerializedName("durataAsta")
  private Integer durataAsta = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("isATurni")
  private Boolean isATurni = null;

  @SerializedName("isSingle")
  private Boolean isSingle = null;

  @SerializedName("mantra")
  private Boolean mantra = null;

  @SerializedName("maxA")
  private Integer maxA = null;

  @SerializedName("maxC")
  private Integer maxC = null;

  @SerializedName("maxD")
  private Integer maxD = null;

  @SerializedName("maxP")
  private Integer maxP = null;

  @SerializedName("minA")
  private Integer minA = null;

  @SerializedName("minC")
  private Integer minC = null;

  @SerializedName("minD")
  private Integer minD = null;

  @SerializedName("minP")
  private Integer minP = null;

  @SerializedName("numeroAcquisti")
  private Integer numeroAcquisti = null;

  @SerializedName("numeroGiocatori")
  private Integer numeroGiocatori = null;

  @SerializedName("numeroMinAcquisti")
  private Integer numeroMinAcquisti = null;

  public Configurazione budget(Integer budget) {
    this.budget = budget;
    return this;
  }

   /**
   * Get budget
   * @return budget
  **/
  @ApiModelProperty(value = "")
  public Integer getBudget() {
    return budget;
  }

  public void setBudget(Integer budget) {
    this.budget = budget;
  }

  public Configurazione durataAsta(Integer durataAsta) {
    this.durataAsta = durataAsta;
    return this;
  }

   /**
   * Get durataAsta
   * @return durataAsta
  **/
  @ApiModelProperty(value = "")
  public Integer getDurataAsta() {
    return durataAsta;
  }

  public void setDurataAsta(Integer durataAsta) {
    this.durataAsta = durataAsta;
  }

  public Configurazione id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Configurazione isATurni(Boolean isATurni) {
    this.isATurni = isATurni;
    return this;
  }

   /**
   * Get isATurni
   * @return isATurni
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsATurni() {
    return isATurni;
  }

  public void setIsATurni(Boolean isATurni) {
    this.isATurni = isATurni;
  }

  public Configurazione isSingle(Boolean isSingle) {
    this.isSingle = isSingle;
    return this;
  }

   /**
   * Get isSingle
   * @return isSingle
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsSingle() {
    return isSingle;
  }

  public void setIsSingle(Boolean isSingle) {
    this.isSingle = isSingle;
  }

  public Configurazione mantra(Boolean mantra) {
    this.mantra = mantra;
    return this;
  }

   /**
   * Get mantra
   * @return mantra
  **/
  @ApiModelProperty(value = "")
  public Boolean isMantra() {
    return mantra;
  }

  public void setMantra(Boolean mantra) {
    this.mantra = mantra;
  }

  public Configurazione maxA(Integer maxA) {
    this.maxA = maxA;
    return this;
  }

   /**
   * Get maxA
   * @return maxA
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxA() {
    return maxA;
  }

  public void setMaxA(Integer maxA) {
    this.maxA = maxA;
  }

  public Configurazione maxC(Integer maxC) {
    this.maxC = maxC;
    return this;
  }

   /**
   * Get maxC
   * @return maxC
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxC() {
    return maxC;
  }

  public void setMaxC(Integer maxC) {
    this.maxC = maxC;
  }

  public Configurazione maxD(Integer maxD) {
    this.maxD = maxD;
    return this;
  }

   /**
   * Get maxD
   * @return maxD
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxD() {
    return maxD;
  }

  public void setMaxD(Integer maxD) {
    this.maxD = maxD;
  }

  public Configurazione maxP(Integer maxP) {
    this.maxP = maxP;
    return this;
  }

   /**
   * Get maxP
   * @return maxP
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxP() {
    return maxP;
  }

  public void setMaxP(Integer maxP) {
    this.maxP = maxP;
  }

  public Configurazione minA(Integer minA) {
    this.minA = minA;
    return this;
  }

   /**
   * Get minA
   * @return minA
  **/
  @ApiModelProperty(value = "")
  public Integer getMinA() {
    return minA;
  }

  public void setMinA(Integer minA) {
    this.minA = minA;
  }

  public Configurazione minC(Integer minC) {
    this.minC = minC;
    return this;
  }

   /**
   * Get minC
   * @return minC
  **/
  @ApiModelProperty(value = "")
  public Integer getMinC() {
    return minC;
  }

  public void setMinC(Integer minC) {
    this.minC = minC;
  }

  public Configurazione minD(Integer minD) {
    this.minD = minD;
    return this;
  }

   /**
   * Get minD
   * @return minD
  **/
  @ApiModelProperty(value = "")
  public Integer getMinD() {
    return minD;
  }

  public void setMinD(Integer minD) {
    this.minD = minD;
  }

  public Configurazione minP(Integer minP) {
    this.minP = minP;
    return this;
  }

   /**
   * Get minP
   * @return minP
  **/
  @ApiModelProperty(value = "")
  public Integer getMinP() {
    return minP;
  }

  public void setMinP(Integer minP) {
    this.minP = minP;
  }

  public Configurazione numeroAcquisti(Integer numeroAcquisti) {
    this.numeroAcquisti = numeroAcquisti;
    return this;
  }

   /**
   * Get numeroAcquisti
   * @return numeroAcquisti
  **/
  @ApiModelProperty(value = "")
  public Integer getNumeroAcquisti() {
    return numeroAcquisti;
  }

  public void setNumeroAcquisti(Integer numeroAcquisti) {
    this.numeroAcquisti = numeroAcquisti;
  }

  public Configurazione numeroGiocatori(Integer numeroGiocatori) {
    this.numeroGiocatori = numeroGiocatori;
    return this;
  }

   /**
   * Get numeroGiocatori
   * @return numeroGiocatori
  **/
  @ApiModelProperty(value = "")
  public Integer getNumeroGiocatori() {
    return numeroGiocatori;
  }

  public void setNumeroGiocatori(Integer numeroGiocatori) {
    this.numeroGiocatori = numeroGiocatori;
  }

  public Configurazione numeroMinAcquisti(Integer numeroMinAcquisti) {
    this.numeroMinAcquisti = numeroMinAcquisti;
    return this;
  }

   /**
   * Get numeroMinAcquisti
   * @return numeroMinAcquisti
  **/
  @ApiModelProperty(value = "")
  public Integer getNumeroMinAcquisti() {
    return numeroMinAcquisti;
  }

  public void setNumeroMinAcquisti(Integer numeroMinAcquisti) {
    this.numeroMinAcquisti = numeroMinAcquisti;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Configurazione configurazione = (Configurazione) o;
    return Objects.equals(this.budget, configurazione.budget) &&
        Objects.equals(this.durataAsta, configurazione.durataAsta) &&
        Objects.equals(this.id, configurazione.id) &&
        Objects.equals(this.isATurni, configurazione.isATurni) &&
        Objects.equals(this.isSingle, configurazione.isSingle) &&
        Objects.equals(this.mantra, configurazione.mantra) &&
        Objects.equals(this.maxA, configurazione.maxA) &&
        Objects.equals(this.maxC, configurazione.maxC) &&
        Objects.equals(this.maxD, configurazione.maxD) &&
        Objects.equals(this.maxP, configurazione.maxP) &&
        Objects.equals(this.minA, configurazione.minA) &&
        Objects.equals(this.minC, configurazione.minC) &&
        Objects.equals(this.minD, configurazione.minD) &&
        Objects.equals(this.minP, configurazione.minP) &&
        Objects.equals(this.numeroAcquisti, configurazione.numeroAcquisti) &&
        Objects.equals(this.numeroGiocatori, configurazione.numeroGiocatori) &&
        Objects.equals(this.numeroMinAcquisti, configurazione.numeroMinAcquisti);
  }

  @Override
  public int hashCode() {
    return Objects.hash(budget, durataAsta, id, isATurni, isSingle, mantra, maxA, maxC, maxD, maxP, minA, minC, minD, minP, numeroAcquisti, numeroGiocatori, numeroMinAcquisti);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Configurazione {\n");
    
    sb.append("    budget: ").append(toIndentedString(budget)).append("\n");
    sb.append("    durataAsta: ").append(toIndentedString(durataAsta)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isATurni: ").append(toIndentedString(isATurni)).append("\n");
    sb.append("    isSingle: ").append(toIndentedString(isSingle)).append("\n");
    sb.append("    mantra: ").append(toIndentedString(mantra)).append("\n");
    sb.append("    maxA: ").append(toIndentedString(maxA)).append("\n");
    sb.append("    maxC: ").append(toIndentedString(maxC)).append("\n");
    sb.append("    maxD: ").append(toIndentedString(maxD)).append("\n");
    sb.append("    maxP: ").append(toIndentedString(maxP)).append("\n");
    sb.append("    minA: ").append(toIndentedString(minA)).append("\n");
    sb.append("    minC: ").append(toIndentedString(minC)).append("\n");
    sb.append("    minD: ").append(toIndentedString(minD)).append("\n");
    sb.append("    minP: ").append(toIndentedString(minP)).append("\n");
    sb.append("    numeroAcquisti: ").append(toIndentedString(numeroAcquisti)).append("\n");
    sb.append("    numeroGiocatori: ").append(toIndentedString(numeroGiocatori)).append("\n");
    sb.append("    numeroMinAcquisti: ").append(toIndentedString(numeroMinAcquisti)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

