/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Fantarose
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-09-16T10:12:51.528Z")
public class Fantarose {
  @SerializedName("costo")
  private Integer costo = null;

  @SerializedName("idAllenatore")
  private Integer idAllenatore = null;

  @SerializedName("idGiocatore")
  private Integer idGiocatore = null;

  @SerializedName("sqlTime")
  private String sqlTime = null;

  public Fantarose costo(Integer costo) {
    this.costo = costo;
    return this;
  }

   /**
   * Get costo
   * @return costo
  **/
  @ApiModelProperty(value = "")
  public Integer getCosto() {
    return costo;
  }

  public void setCosto(Integer costo) {
    this.costo = costo;
  }

  public Fantarose idAllenatore(Integer idAllenatore) {
    this.idAllenatore = idAllenatore;
    return this;
  }

   /**
   * Get idAllenatore
   * @return idAllenatore
  **/
  @ApiModelProperty(value = "")
  public Integer getIdAllenatore() {
    return idAllenatore;
  }

  public void setIdAllenatore(Integer idAllenatore) {
    this.idAllenatore = idAllenatore;
  }

  public Fantarose idGiocatore(Integer idGiocatore) {
    this.idGiocatore = idGiocatore;
    return this;
  }

   /**
   * Get idGiocatore
   * @return idGiocatore
  **/
  @ApiModelProperty(value = "")
  public Integer getIdGiocatore() {
    return idGiocatore;
  }

  public void setIdGiocatore(Integer idGiocatore) {
    this.idGiocatore = idGiocatore;
  }

  public Fantarose sqlTime(String sqlTime) {
    this.sqlTime = sqlTime;
    return this;
  }

   /**
   * Get sqlTime
   * @return sqlTime
  **/
  @ApiModelProperty(value = "")
  public String getSqlTime() {
    return sqlTime;
  }

  public void setSqlTime(String sqlTime) {
    this.sqlTime = sqlTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Fantarose fantarose = (Fantarose) o;
    return Objects.equals(this.costo, fantarose.costo) &&
        Objects.equals(this.idAllenatore, fantarose.idAllenatore) &&
        Objects.equals(this.idGiocatore, fantarose.idGiocatore) &&
        Objects.equals(this.sqlTime, fantarose.sqlTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(costo, idAllenatore, idGiocatore, sqlTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Fantarose {\n");
    
    sb.append("    costo: ").append(toIndentedString(costo)).append("\n");
    sb.append("    idAllenatore: ").append(toIndentedString(idAllenatore)).append("\n");
    sb.append("    idGiocatore: ").append(toIndentedString(idGiocatore)).append("\n");
    sb.append("    sqlTime: ").append(toIndentedString(sqlTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

