/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Calendar;
import java.io.IOException;

/**
 * Giocatori
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-09-16T10:12:51.528Z")
public class Giocatori {
  @SerializedName("dataNascita")
  private Calendar dataNascita = null;

  @SerializedName("fvm")
  private Double fvm = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("macroRuolo")
  private String macroRuolo = null;

  @SerializedName("nome")
  private String nome = null;

  @SerializedName("quotazione")
  private Integer quotazione = null;

  @SerializedName("ruolo")
  private String ruolo = null;

  @SerializedName("squadra")
  private String squadra = null;

  public Giocatori dataNascita(Calendar dataNascita) {
    this.dataNascita = dataNascita;
    return this;
  }

   /**
   * Get dataNascita
   * @return dataNascita
  **/
  @ApiModelProperty(value = "")
  public Calendar getDataNascita() {
    return dataNascita;
  }

  public void setDataNascita(Calendar dataNascita) {
    this.dataNascita = dataNascita;
  }

  public Giocatori fvm(Double fvm) {
    this.fvm = fvm;
    return this;
  }

   /**
   * Get fvm
   * @return fvm
  **/
  @ApiModelProperty(value = "")
  public Double getFvm() {
    return fvm;
  }

  public void setFvm(Double fvm) {
    this.fvm = fvm;
  }

  public Giocatori id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Giocatori macroRuolo(String macroRuolo) {
    this.macroRuolo = macroRuolo;
    return this;
  }

   /**
   * Get macroRuolo
   * @return macroRuolo
  **/
  @ApiModelProperty(value = "")
  public String getMacroRuolo() {
    return macroRuolo;
  }

  public void setMacroRuolo(String macroRuolo) {
    this.macroRuolo = macroRuolo;
  }

  public Giocatori nome(String nome) {
    this.nome = nome;
    return this;
  }

   /**
   * Get nome
   * @return nome
  **/
  @ApiModelProperty(value = "")
  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }

  public Giocatori quotazione(Integer quotazione) {
    this.quotazione = quotazione;
    return this;
  }

   /**
   * Get quotazione
   * @return quotazione
  **/
  @ApiModelProperty(value = "")
  public Integer getQuotazione() {
    return quotazione;
  }

  public void setQuotazione(Integer quotazione) {
    this.quotazione = quotazione;
  }

  public Giocatori ruolo(String ruolo) {
    this.ruolo = ruolo;
    return this;
  }

   /**
   * Get ruolo
   * @return ruolo
  **/
  @ApiModelProperty(value = "")
  public String getRuolo() {
    return ruolo;
  }

  public void setRuolo(String ruolo) {
    this.ruolo = ruolo;
  }

  public Giocatori squadra(String squadra) {
    this.squadra = squadra;
    return this;
  }

   /**
   * Get squadra
   * @return squadra
  **/
  @ApiModelProperty(value = "")
  public String getSquadra() {
    return squadra;
  }

  public void setSquadra(String squadra) {
    this.squadra = squadra;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Giocatori giocatori = (Giocatori) o;
    return Objects.equals(this.dataNascita, giocatori.dataNascita) &&
        Objects.equals(this.fvm, giocatori.fvm) &&
        Objects.equals(this.id, giocatori.id) &&
        Objects.equals(this.macroRuolo, giocatori.macroRuolo) &&
        Objects.equals(this.nome, giocatori.nome) &&
        Objects.equals(this.quotazione, giocatori.quotazione) &&
        Objects.equals(this.ruolo, giocatori.ruolo) &&
        Objects.equals(this.squadra, giocatori.squadra);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataNascita, fvm, id, macroRuolo, nome, quotazione, ruolo, squadra);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Giocatori {\n");
    
    sb.append("    dataNascita: ").append(toIndentedString(dataNascita)).append("\n");
    sb.append("    fvm: ").append(toIndentedString(fvm)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    macroRuolo: ").append(toIndentedString(macroRuolo)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    quotazione: ").append(toIndentedString(quotazione)).append("\n");
    sb.append("    ruolo: ").append(toIndentedString(ruolo)).append("\n");
    sb.append("    squadra: ").append(toIndentedString(squadra)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

