/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SpesoTotale
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-09-16T10:12:51.528Z")
public class SpesoTotale {
  @SerializedName("conta")
  private Long conta = null;

  @SerializedName("costo")
  private Long costo = null;

  @SerializedName("macroRuolo")
  private String macroRuolo = null;

  @SerializedName("nome")
  private String nome = null;

  public SpesoTotale conta(Long conta) {
    this.conta = conta;
    return this;
  }

   /**
   * Get conta
   * @return conta
  **/
  @ApiModelProperty(value = "")
  public Long getConta() {
    return conta;
  }

  public void setConta(Long conta) {
    this.conta = conta;
  }

  public SpesoTotale costo(Long costo) {
    this.costo = costo;
    return this;
  }

   /**
   * Get costo
   * @return costo
  **/
  @ApiModelProperty(value = "")
  public Long getCosto() {
    return costo;
  }

  public void setCosto(Long costo) {
    this.costo = costo;
  }

  public SpesoTotale macroRuolo(String macroRuolo) {
    this.macroRuolo = macroRuolo;
    return this;
  }

   /**
   * Get macroRuolo
   * @return macroRuolo
  **/
  @ApiModelProperty(value = "")
  public String getMacroRuolo() {
    return macroRuolo;
  }

  public void setMacroRuolo(String macroRuolo) {
    this.macroRuolo = macroRuolo;
  }

  public SpesoTotale nome(String nome) {
    this.nome = nome;
    return this;
  }

   /**
   * Get nome
   * @return nome
  **/
  @ApiModelProperty(value = "")
  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpesoTotale spesoTotale = (SpesoTotale) o;
    return Objects.equals(this.conta, spesoTotale.conta) &&
        Objects.equals(this.costo, spesoTotale.costo) &&
        Objects.equals(this.macroRuolo, spesoTotale.macroRuolo) &&
        Objects.equals(this.nome, spesoTotale.nome);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conta, costo, macroRuolo, nome);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpesoTotale {\n");
    
    sb.append("    conta: ").append(toIndentedString(conta)).append("\n");
    sb.append("    costo: ").append(toIndentedString(costo)).append("\n");
    sb.append("    macroRuolo: ").append(toIndentedString(macroRuolo)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

