/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TimeZone
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-09-16T10:12:51.528Z")
public class TimeZone {
  @SerializedName("displayName")
  private String displayName = null;

  @SerializedName("dstsavings")
  private Integer dstsavings = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("rawOffset")
  private Integer rawOffset = null;

  public TimeZone displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public TimeZone dstsavings(Integer dstsavings) {
    this.dstsavings = dstsavings;
    return this;
  }

   /**
   * Get dstsavings
   * @return dstsavings
  **/
  @ApiModelProperty(value = "")
  public Integer getDstsavings() {
    return dstsavings;
  }

  public void setDstsavings(Integer dstsavings) {
    this.dstsavings = dstsavings;
  }

  public TimeZone id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TimeZone rawOffset(Integer rawOffset) {
    this.rawOffset = rawOffset;
    return this;
  }

   /**
   * Get rawOffset
   * @return rawOffset
  **/
  @ApiModelProperty(value = "")
  public Integer getRawOffset() {
    return rawOffset;
  }

  public void setRawOffset(Integer rawOffset) {
    this.rawOffset = rawOffset;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeZone timeZone = (TimeZone) o;
    return Objects.equals(this.displayName, timeZone.displayName) &&
        Objects.equals(this.dstsavings, timeZone.dstsavings) &&
        Objects.equals(this.id, timeZone.id) &&
        Objects.equals(this.rawOffset, timeZone.rawOffset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayName, dstsavings, id, rawOffset);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeZone {\n");
    
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    dstsavings: ").append(toIndentedString(dstsavings)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rawOffset: ").append(toIndentedString(rawOffset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

